apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: pod-with-env
  name: pod-with-env
spec:
  containers:
  - env:
    - name: hostname
      value: test
    image: nginx
    name: pod-with-env
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
