---
apiVersion: v1
data:
  password: V2VsY29tZTE=
  username: QWhtZWQ=
kind: Secret
metadata:
  name: env-secret
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-with-env-secretkeyref
  name: pod-with-env-from-secretkeyref
spec:
  containers:
  - env:
    - name: username
      valueFrom:
        secretKeyRef:
          name: env-secret
          key: username
    - name: password
      valueFrom:
        secretKeyRef:
          name: env-secret
          key: password
    image: nginx
    name: pod-with-env-secretkeyref
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

