---
apiVersion: v1
data:
  password: V2VsY29tZTE=
  username: QWhtZWQ=
kind: Secret
metadata:
  name: envfrom-secret
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-with-envfrom-secret
  name: pod-with-envfrom-secret
spec:
  containers:
  - envFrom:
    - secretRef:
        name: envfrom-secret
    image: nginx
    name: pod-with-envfrom-secretref
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always

