apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-with-env-resourcefieldref
  name: pod-with-env-resourcefieldref
spec:
  containers:
  - env:
    - name: memory-available
      valueFrom:
        resourceFieldRef:
          containerName: pod-with-env-resourcefieldref
          resource: requests.memory
    image: nginx
    name: pod-with-env-resourcefieldref
    resources:
      requests:
        memory: 100Mi
  dnsPolicy: ClusterFirst
  restartPolicy: Always

