---
apiVersion: v1
kind: Namespace
metadata:
  name: mynamespace
spec: {}
---
apiVersion: v1
kind: Pod
metadata:
  name: init-cont-demo
  namespace: mynamespace
spec:
  containers:
  - name: nginx
    image: nginx
    command:
      - sleep
      - "10000"
  initContainers:
  - name: initcont
    image: busybox
    command: ['sh', '-c', 'mkdir /mydata; touch /mydata/myfile.txt']
  
