---
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod
  labels:
    name: simple
spec:
  containers:
  - args:
    - sleep
    - infinity
    image: centos
    name: simple-con
  restartPolicy: Never
