apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-with-hostpath
spec:
  containers:
  - name: pod-container1
    image: nginx
    volumeMounts:
    - name: hostpath1
      mountPath: /tmp/test
    - name: hostpathfile
      mountPath: /tmp/test2
  tolerations:
  - effect: NoSchedule
    key: node-role.kubernetes.io/master
  nodeSelector:
    node-role.kubernetes.io/master: ""
  volumes:
  - name: hostpath1
    hostPath:
      path: /tmp/new/
      type: DirectoryOrCreate 			# If The Directory didn't exist, it gonna be created
  - name: hostpathfile
    hostPath:
      path: /tmp/new/file
      type: FileOrCreate			# If The File didn't exist, it gonna be created
