apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-with-shared-lib
spec:
  containers:
  - name: pod-container1
    image: nginx
    volumeMounts:
    - name: docker-lib
      mountPath: /var/lib/docker
      readOnly: true 					# ReadOnly 
    tolerations:
    - effect: NoSchedule
      key: node-role.kubernetes.io/master
    nodeSelector:
      node-role.kubernetes.io/master: ""
  volumes:
  - name: docker-lib
    hostPath:
      path: /var/lib/docker
      type: Directory
