---
apiVersion: v1
data:
  password: V2VsY29tZTE=
  usernme: d2FlbA==
kind: Secret
metadata:
  name: storage
---
apiVersion: v1
kind: Pod
metadata:
  name: simple-pod-with-secret-volume
spec:
  containers:
  - name: con-with-secret-volume
    image: nginx
    volumeMounts:
    - name: storage-secret
      mountPath: /tmp/
  volumes:
  - name: storage-secret
    secret:
      secretName: storage
