apiVersion: v1
data:
  name: blabla
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: projected-configmap
---
apiVersion: v1
data:
  username: SGFtYWtp
kind: Secret
metadata:
  creationTimestamp: null
  name: projected-user
---
apiVersion: v1
data:
  password: bmF3ZWVoYTE=
kind: Secret
metadata:
  creationTimestamp: null
  name: projected-pass
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-with-projected-volume
spec:
  containers:
  - name: pod-with-projected-volume
    image: busybox
    args:
    - sleep
    - "86400"
    volumeMounts:
    - name: all-in-one
      mountPath: "/projected-volume"
      readOnly: true
  volumes:
  - name: all-in-one
    projected:
      sources:
      - secret:
          name: projected-user
      - secret:
          name: projected-pass
      - configMap:
          name: projected-configmap
