apiVersion: v1
kind: Pod
metadata:
  name: directoryorcreate-demo
spec:
  containers:
  - image: nginx
    name: dirorcreate-container
    volumeMounts:
    - mountPath: /test-pd
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      path: /datadir
      type: DirectoryOrCreate
# Directory Should be exist
