apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: emptydir-test
  name: emptydir-test
spec:
  containers:
  - image: nginx
    name: emptydir-test
    volumeMounts:
    - name: test
      mountPath: /test
  volumes:
  - name: test
    emptyDir: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
