---
apiVersion: v1
kind: Namespace
metadata:
  name: podspec
spec:
  finalizers:
  - kubernetes
---
apiVersion: v1
kind: Pod
metadata:
  name: podblabla
  namespace: podspec
  labels:
    app: blabla
spec:
  containers:
  - name: con1
    image: centos
    resources:
      limits:
        memory: "500Mi"
        cpu: "1.0"
      requests:
        memory: "250Mi"
        cpu: ".5"
    command:
      - sleep
      - "3600"
  securityContext:
    runAsUser: 2000
  restartPolicy: Never
