---
apiVersion: v1
kind: Pod
metadata:
  name: multivol-pod
  labels:
    app: test
    env: dev
spec:
  containers:
  - name: multivol-pod
    image: nginx
    command:
      - sleep
      - "3600"
    volumeMounts:
    - name: cache-dir
      mountPath: /cache
    - name: dockerlib
      mountPath: /var/lib/docker
  volumes:
  - name: cache-dir
    emptyDir: {}
  - name: dockerlib
    hostPath:
      path: /var/lib/docker
      type: Directory

